remote_theme: godalming123/minimal
plugins:
- jekyll-remote-theme 
title: "Congrats, you found an NFC tag!"
description: "But really tho.. You might want to check your life choices. Why would you scan an NFC tag you just found? That is not very safe.  Anyhow - finders keepers, you're welcome."
show_downloads: false
google_analytics: "G-RQR0G235HD"
logo: /zebra1.jpeg
